name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ivancea/jekyll-mac-renderer@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
